services:
  postgres:
    image: postgres:16-alpine
    container_name: tickets-for-you-postgres
    environment:
      POSTGRES_DB: tickets_for_you
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: